### PR TITLE
Update dependencies and (mostly) clear npm audit

### LINKED ISSUE #187: hoek security issue (downstream dependency)
`npm audit` yields the following issue which cannot be automatically resolved:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ [redacted SHA]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ [redacted SHA]                                               │
│               │ > ember-cli-sass > broccoli-sass-source-maps > node-sass >   │
│               │ node-gyp > request > hawk > boom > hoek                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

Fix is presumably dependent on https://github.com/nodejs/node-gyp/pull/1492 - this is just to track.

### PR DESCRIPTION
**Pull request by gorner**
- ran `ember-cli-update` to update ember-cli addon blueprint to ~~3.3~~ 3.4, and updated acceptance tests to work with [current test APIs](https://github.com/emberjs/ember-qunit/blob/master/docs/migration.md)
- cleared most `npm audit` issues; resolves #187 ~~(but excluding one minor [issue](https://github.com/ember-cli/ember-try/issues/200) dependent on pending ember-try 1.0 release)~~

### CODE REVIEW

**Comment by jbailey4** [comment]
@gorner Looks good, could you rebase and fix the couple merge conflicts.

**Comment by gorner** [comment]
@jbailey4 Done.

**Comment by blkeller** [comment]
While you're in here, is there any chance you would be able to bump the 'broccoli-funnel' dependency to 2.0.1 (the latest)?  npm is still throwing a deprecation warning for 'exists-sync', which 'broccoli-funnel' depended on [until version 2.0.1](https://github.com/broccolijs/broccoli-funnel/commit/00395f0699b99738f867e9cc6ca1915d82f9609b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

According to their [changelog](https://github.com/broccolijs/broccoli-funnel/blob/master/CHANGELOG.md), it looks like the reason for the major version bump was simply because they dropped support for node 0.12.  Meanwhile, this PR already declares node 6.x as the minimum supported version for 'ember-cli-sass'.

**Comment by jrjohnson** [comment]
Friendly bump. Would love to see this merged as it will remove a few distracting build warnings from our app now that broccoli-funnel is updated here.

**Comment by BryanCrotaz** [comment]
bump - this is the last addon we use that requires babel 5.x

**Comment by gorner** [comment]
@aexmachina if there's anything else you need for this, please let me know!

**Comment by aexmachina** [comment]
I assume that this would be a patch-level version bump?

**Comment by gorner** [comment]
@aexmachina The change in acceptable node versions (package.json line 61) _might_ be interpreted as a breaking change, though Node 4.x has been already end-of-life since this past April. Otherwise I don't see anything that would qualify as an enhancement or breaking change.

**Comment by jrjohnson** [comment]
I have seen other addons mark a major version when dropping node 4.

**Pull request merged**
