### PR TITLE
Fix/addon support

### LINKED ISSUE #105: Cannot read property 'sassOptions' of undefined
Traces back to this:
```js
    var options = (this.app && this.app.options.sassOptions) || {};
```
Appears to be because of addon usage (I'm using it within an addon). My `included` hook is correct, so hack specified in the README instructions is no longer good enough to trick it into having access to `options`.

### PR DESCRIPTION
**Pull request by runspired**
This resolves #105 #96 

This may help #83

### CODE REVIEW

**Comment by aexmachina** [comment]
LGTM, @stefanpenner does this seem reasonable to you?

**Comment by aexmachina** [comment]
Oh, and thanks!

**Comment by aexmachina** [comment]
What about @dukex, are you able to confirm this PR?

**Comment by dukex** [comment]
Thanks @runspired, LGTM!

**Comment by aexmachina** [comment]
Published v5.3.0

**Comment by runspired** [comment]
Thanks!

**Pull request merged**
