### PR TITLE
Update to work with ember-cli 0.2.0.

### PR DESCRIPTION
**Pull request by abuiles**
* Users setupPreprocessorRegistry
* Move config options to config/environment.js, since Brocfile options are going away http://cl.ly/image/1T3L3l0d1B1w

### CODE REVIEW

**Comment by aexmachina** [comment]
Awesome, nice work :+1: Have confirmed that it's backwards-compatible with pre ember-cli@0.2.0-beta.1

**Comment by aexmachina** [comment]
Published as 3.0.4.

**Comment by aexmachina** [comment]
And as 3.1.0-beta.2 if you want source maps as well :)

**Comment by abuiles** [comment]
@aexmachina cool, I think is important if there are any release notes to mention that the config options are now moved to `config/environment.js` and not the Brocfile.

I'm also still trying to figure it out how to extend the options from another addon, specifically https://github.com/unionups/ember-cli-bootstrap-sass

**Comment by abuiles** [comment]
@aexmachina ignore :), just saw your other commit

**Comment by aexmachina** [comment]
Actually @abuiles, there's issues with this. Can you chat on Gitter?

**Comment by abuiles** [comment]
@aexmachina I'm there.

**Pull request merged**
