### PR TITLE
Allow for passing generated files from the styles tree through to dist/

### PR DESCRIPTION
**Pull request by dfreeman**
This PR adds a `passthrough` option that allows for artifacts produced earlier in styles processing to be emitted into the final output in `dist`.

@chriskrycho can offer some details on the situation he ran into where this would be useful to have.

### CODE REVIEW

**Comment by dfreeman** [comment]
(It looks like tests are failing due to https://github.com/ember-cli/ember-cli/issues/7472)

**Comment by chriskrycho** [comment]
Our main Ember.js app is used for white-labeling, and we have a slightly quirky setup as a result.

- We have a development build which uses ember-cli-sass so we can have development Just Work™️, which uses the base styles for the app.
- For the production build of the CSS for the app, we pull the `.scss` files from the tree in and merge them in an appropriate way with the customizations for each white-labeled client setup.

Accordingly, we need a way to essentially *turn off* the compilation phase for production, while using it for development. We _also_ are now aiming to use this in conjunction with ember-css-modules, so we're looking for the generated file from that to be incorporated into our normal build for dev, but split out as a standalone file that can be ingested into our build process for the white-labeling.

An example of what that would look like in-app (with the options for ember-css-modules set to generate a file named `app/styles/_modules.scss` from the CSS Modules):

```js
sassOptions: {
  // other options
  passthrough: {
    srcDir: 'app/styles',
    destDir: 'scss-for-whitelabeling',
    include: '_modules.scss',
  },
},
```

(In our scenario, the `sassOptions` hash will actually be customized depending on build environment, but the gist is clear enough this way.)

**Comment by chriskrycho** [comment]
@aexmachina (a) do you mind re-triggering the CI build and (b) do you have thoughts on this? It's pretty important for our use case and while we *can* just open a fork that supports this and track ember-cli-sass, we'd really prefer not to.

**Comment by aexmachina** [comment]
This looks both reasonable and useful to me. I've kicked off the build again... Looks like there might be a [workaround to the failing Travis build](https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-348198699) if you want to get this merged before the problem is resolved in Travis.

**Comment by chriskrycho** [comment]
Awesome! I’ll push a commit (err, or I guess PR Dan’s PR?) with the tweak tomorrow or Tuesday.

**Comment by dfreeman** [comment]
Pushed an update to use [the workaround that ember-cli went with for new projects](https://github.com/ember-cli/ember-addon-output/blob/master/testem.js).

**Comment by aexmachina** [comment]
Published v7.2.0 :tada:

**Comment by chriskrycho** [comment]
Thanks!

**Pull request merged**
