### PR TITLE
Add addon tests (WIP)

### PR DESCRIPTION
**Pull request by rwwagner90**

### CODE REVIEW

**Comment by rwwagner90** [comment]
@aexmachina I did an `ember init` inside the current code to generate most of the addon structure, and manually added in some of the things it missed. However, running `ember test` seems to blow up on me and I am not sure why.

**Comment by Dhaulagiri** [comment]
@rwwagner90 you need to add `ember-cli-babel` to dependencies and then the tests should work 💯

**Comment by rwwagner90** [comment]
Thanks @Dhaulagiri that did the trick!

**Comment by rwwagner90** [comment]
@aexmachina could you give this a look and make sure everything still works? There were not any tests written for the functionality were there?

**Comment by rwwagner90** [comment]
@aexmachina please let me know if everything appears to work for you and if you have any feedback 😄

**Comment by aexmachina** [comment]
Sorry @rwwagner90, I've been very busy of late. Thanks for your efforts, I'm hoping to get this later this week.

**Comment by aexmachina** [comment]
Thanks, tests incoming...

**Pull request merged**
